### PR TITLE
duped in attributes

### PR DESCRIPTION
**Pull request by bglusman**
@devmanhinton

### CODE REVIEW

**Comment by devmanhinton** [comment]
@bglusman Added deletion of other duplicate attribute documentation :D

**Comment by devmanhinton** [comment]
If you approve can you comment & then I will merge

**Comment by bglusman** [comment]
@devmanhinton oh I forgot... I think I only meant to remove the one you removed, maybe should leave the other one in syntax doc if we're leaving that around as an overview? your call, fine either way.

**Comment by devmanhinton** [comment]
Yeah that sounds better to me. I'll push that up in another branch real quick

**Pull request closed without merging**
