### PR TITLE
Readme notes

### PR DESCRIPTION
**Pull request by bglusman**
@yaymukund @sethbannon readme note for reviewers on pending change

### CODE REVIEW

**Comment by yaymukund** [comment]
I don't think we need to add this giant disclaimer.

a) We'll do a version bump when we make this change, so it's not like apps will break.
b) It's in beta, so they should expect changes to the public interface. It's one of the acknowledged tradeoffs to trying out shiny new things.

**Comment by bglusman** [comment]
cc'ing seth via email since he may not follow github discussions...

I think we can and should remove it as soon as it's merged in, and perhaps
modify the language, but it's a big enough change and there's a viable
option for them that anyone who happens to be playing with it for now
should know about it.  It's temporary, but I think kind of important to
someone providing feedback or trying it out.

Brian Glusman - brian@amicushq.com
215-460-9585 - _cell_
_Twitter_: @amicushq

**Comment by devmanhinton** [comment]
I actually agree with Mukund on this. Brian, I think it is great to think of, and try to make these beta developers feel good, but since it is labeled "beta" such extra note impending change is unnecessary :D

**Comment by sethbannon** [comment]
I do follow github discussions :eyes: 

I'll defer to the wisdom of you guys on this one.

**Pull request closed without merging**
