### PR TITLE
Change headers so that top level headers are EndDash and Documentation. ...

### PR DESCRIPTION
**Pull request by devmanhinton**
@bglusman @FredericoAndrade 

This changes the headers so the auto parsing into enddash.com will work as desired

EndDash -- gettingStarted
              -- PlayingWithExamples

Documentation - Section1
                            --Sub Section1
                            --Sub Section2
                       - Section 2
                      etc..

### CODE REVIEW

**Comment by bglusman** [comment]
freddie is playing with styling this, when hes ready we can change it both
places

On Wednesday, November 13, 2013, amicus-jenkins wrote:

> Can one of the admins verify this patch?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Amicus/end-dash/pull/150#issuecomment-28447864
> .

## 

Brian Glusman - brian@amicushq.com
215-460-9585 - _cell_
_Twitter_: @amicushq

**Comment by yaymukund** [comment]
:+1:

**Comment by bglusman** [comment]
@FredericoAndrade we had a different branch for this I think you had been checking styling on, lmk if want me to help but we should preview and get that looking ok on your machine then maybe PR it together or something.

**Comment by bglusman** [comment]
I'm going to close this but @FredericoAndrade if you still want to do this we can, but I'll leave that to you, ask if you need help.

**Pull request closed without merging**
