### PR TITLE
delete require extensions, not used in tests or browser anymore

### PR DESCRIPTION
**Pull request by bglusman**
@yaymukund

### CODE REVIEW

**Comment by yaymukund** [comment]
Looks good to me, but I totally thought this was getting used... how have you tested this?

If you haven't already, you can test enddash in brief by symlinking `app/assets/javascripts/components/end-dash`

**Comment by bglusman** [comment]
@yaymukund yep, tested by running all brief mocha tests, and poking around with some browser testing...  can't think of anything else to test, but lmk if you think of anything, or @devmanhinton if you have ideas/saw possible implications of removing this.

**Comment by devmanhinton** [comment]
@bglusman Yeah, if you symLinked and it worked fine. Then this is good with me.

I guess that is deprecated, even in brief, given this in base-backbone:index.js

  var loaders = {
    template: function(templateDir) {
      _(listFiles(templateDir)).each(function(path) {
        var noExt = path.replace(/.js.ed(.erb)?$/, "")
        EndDash.registerTemplate(noExt, fs.readFileSync(path, 'utf8'))
      })
      _(listFiles(templateDir)).each(function(path) {
        var noExt = path.replace(/.js.ed(.erb)?$/, "")
        if(window && window.require) {
          window.require.register(noExt + ".js", function(module) {
            templateCompiler(module, path)
          })
        }
      })
    },

templateDir in this case is /app/assets/javascript/new/templates & that is the only place where there are '.js.ed' files. So this is a safe merge.

**Comment by bglusman** [comment]
Yeah, change was fine in brief.  WIll let one of you two click merge button on this since you both seem OK with it.

**Pull request merged**
