### PR TITLE
Looping on same element

### PR DESCRIPTION
**Pull request by xcoderzach**
I want to be able to write this:

``` html
<ul class="repos-" data-each>
  <li></li>
</ul>
```

not

``` html
<div class="repos-">
  <ul data-each>
    <li></li>
  </ul>
</div>
```

### CODE REVIEW

**Comment by xcoderzach** [comment]
heheheh lul

**Comment by ChrisVoxland** [comment]
@amicus-jenkins test this please (if I'm an admin)

**Comment by tobowers** [comment]
test this please

**Comment by tobowers** [comment]
Are you sure you don't want to write:

``` html
<ul class="repos-">
  <li data-each></li>
</ul>
```

That way for something like a chat room I could say:

``` html
<div class="chats-">
  <p class="totalCount-"></p>
  <ul>
    <li data-each>
      <p class="speaker-"></p>
      <p class="content-"></p>
    </li>
  </ul>
</div>
```

**Comment by bglusman** [comment]
Oh, does his patch prevent doing both ways?  I assumed it just allowed on
same line not required it... if it doesn't allow it I'm with Topper... I'm
more bothered by the need for a placeholder div inside data-each eevn if
theres already a single root element.

On Tuesday, December 3, 2013, Topper Bowers wrote:

> Are you sure you don't want to write:
> 
> <ul class="repos-">
>   <li data-each></li></ul>
> 
> That way for something like a chat room I could say:
> 
> <div class="chats-">
>   <p class="totalCount-"></p>
>   <ul>
>     <li data-each>
>       <p class="speaker-"></p>
>       <p class="content"></p>
>     </li>
>   </ul></div>
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Amicus/end-dash/pull/176#issuecomment-29717900
> .

## 

Brian Glusman - brian@glusman.me
215-460-9585 - _cell_
_Twitter_: @bglusman

**Comment by tobowers** [comment]
@xcoderzach do you disagree that we want

``` html
  <ul class="users-">
    <li data-each> <!-- this is the user scope -->
      <p class="name-"></p>
      <p class="age-"><p>
    </li>
  </ul>
```

**Comment by xcoderzach** [comment]
My fix does both :-)

**Comment by xcoderzach** [comment]
Its really hard to do tables using the nested data-each.  Will post example
when not at phone.

**Comment by tobowers** [comment]
Oh... I just realized maybe you guys don't know that you _can't_ do what I put up there.  EndDash tries to repeat the p tags and fails.

I think maybe that's a bug and not intentional behavior.

@xcoderzach : if what I had worked wouldn't tables be ok to create?

```
<table class="users-">
  <thead>
  <th>name</th>
  </thead>
  <tr data-each>
    <td class="name-"></td>
  </tr>
</table>
```

**Comment by tobowers** [comment]
What I'm talking about would have these corrected tests passing:

https://github.com/Amicus/end-dash/compare/fix-looping-tests?expand=1

**Comment by tobowers** [comment]
I think this is a step forward... so merging this and then following up with a proposed syntax change.

**Pull request merged**
