### PR TITLE
Expose setGetViewFn to the end user

### PR DESCRIPTION
**Pull request by devmanhinton**
@yaymukund This needs to be in here. 

Not sure if require the view a second time is okay? (its fast since node caches the require).

Thoughts?

### CODE REVIEW

**Comment by devmanhinton** [comment]
@yaymukund Calling it a night at least for now but this is necessary to move forwards with the node example app

**Comment by yaymukund** [comment]
Do explain...

**Comment by devmanhinton** [comment]
Look at the code but 

``` javascript
<div data-view="whatever"></div> 
```

relies on the View reaction which relies on a function that is by default undefined, getView. 

In brief, base-backbone deals with setting this up. It does ViewReaction.setGetView(fn...)

So in order to have EndDash work with views we need to expose this function to them.

**Comment by tobowers** [comment]
Is there a way to have a sensible default that will try a require?
- Topper

**Comment by devmanhinton** [comment]
@tobowers Sure, let me write a draft of that and you can let me know what you think

**Pull request closed without merging**
