### PR TITLE
Bump EndDash version

### PR DESCRIPTION
**Pull request by devmanhinton**
@tobowers @yaymukund 

After merge will push tag + PR to brief to test w/ new version

### CODE REVIEW

**Comment by devmanhinton** [comment]
@tobowers @yaymukund Ping

**Comment by yaymukund** [comment]
reviewing

**Comment by yaymukund** [comment]
lgtm once master merges are unfrozen

**Comment by yaymukund** [comment]
Oh right this is enddash, not brief.

**Pull request merged**
